export interface ThemeConfig {
  id: string;
  name: string;
  description: string;
  price: number;
  bg: string;            // Body background color
  cardBg: string;        // Card/Container background color
  border: string;        // Card/Container border color
  text: string;          // General primary text color
  textMuted: string;     // General secondary text color
  primaryBg: string;     // Primary button/accent background color
  primaryHoverBg: string;// Primary button/accent hover state
  primaryText: string;   // Text inside a primary button/accent background
  accentText: string;    // Main highlight text color (replaces text-orange-400)
  accentBg: string;      // Highlight background color (replaces bg-orange-500/10)
  accentBorder: string;  // Highlight border color (replaces border-orange-500/30)
  accentRing: string;    // Focus ring styling
  gradientFrom: string;  // Progressive overload gradient start
  gradientTo: string;    // Progressive overload gradient end
  isLight?: boolean;     // Flag to adjust secondary accents for light mode
  overrideCyan300: string;
  overrideCyan400: string;
  overrideCyan500: string;
  overrideCyan600: string;
  overrideCyanRgb: string;
  overrideZincBackground?: string;
  overrideZincCardBg?: string;
  overrideZincBorder?: string;
  overrideZincText?: string;
  overrideZincTextMuted?: string;
}

export const THEMES: Record<string, ThemeConfig> = {
  orange_dark: {
    id: 'orange_dark',
    name: 'Orange & Dark (Default)',
    description: 'Sleek neon cyber theme with classic orange accents',
    price: 0,
    bg: 'bg-zinc-950',
    cardBg: 'bg-zinc-900',
    border: 'border-zinc-800',
    text: 'text-zinc-100',
    textMuted: 'text-zinc-400',
    primaryBg: 'bg-orange-500',
    primaryHoverBg: 'hover:bg-orange-400',
    primaryText: 'text-zinc-950',
    accentText: 'text-orange-400',
    accentBg: 'bg-orange-500/10',
    accentBorder: 'border-orange-500/30',
    accentRing: 'focus:ring-orange-500',
    gradientFrom: 'from-orange-500',
    gradientTo: 'to-amber-400',
    isLight: false,
    overrideCyan300: '#fdba74',
    overrideCyan400: '#f97316',
    overrideCyan500: '#ea580c',
    overrideCyan600: '#c2410c',
    overrideCyanRgb: '234, 88, 12',
  },
  black_white: {
    id: 'black_white',
    name: 'Noir Monochrome',
    description: 'Stark, luxury high-contrast black and white design',
    price: 150,
    bg: 'bg-black',
    cardBg: 'bg-zinc-900',
    border: 'border-zinc-800',
    text: 'text-white',
    textMuted: 'text-zinc-400',
    primaryBg: 'bg-white',
    primaryHoverBg: 'hover:bg-zinc-200',
    primaryText: 'text-black',
    accentText: 'text-white',
    accentBg: 'bg-white/10',
    accentBorder: 'border-white/30',
    accentRing: 'focus:ring-white',
    gradientFrom: 'from-zinc-500',
    gradientTo: 'to-white',
    isLight: false,
    overrideCyan300: '#e4e4e7',
    overrideCyan400: '#ffffff',
    overrideCyan500: '#ffffff',
    overrideCyan600: '#a1a1aa',
    overrideCyanRgb: '255, 255, 255',
  },
  green_white: {
    id: 'green_white',
    name: 'Mint Meadow (Light)',
    description: 'Fresh off-white design with organic emerald-green accents',
    price: 200,
    bg: 'bg-zinc-50',
    cardBg: 'bg-white',
    border: 'border-zinc-200',
    text: 'text-zinc-900',
    textMuted: 'text-zinc-500',
    primaryBg: 'bg-emerald-600',
    primaryHoverBg: 'hover:bg-emerald-500',
    primaryText: 'text-white',
    accentText: 'text-emerald-600',
    accentBg: 'bg-emerald-50',
    accentBorder: 'border-emerald-200',
    accentRing: 'focus:ring-emerald-500',
    gradientFrom: 'from-emerald-500',
    gradientTo: 'to-amber-500',
    isLight: true,
    overrideCyan300: '#6ee7b7',
    overrideCyan400: '#059669',
    overrideCyan500: '#047857',
    overrideCyan600: '#064e3b',
    overrideCyanRgb: '4, 120, 87',
    overrideZincBackground: '#f4f4f5',
    overrideZincCardBg: '#ffffff',
    overrideZincBorder: '#e4e4e7',
    overrideZincText: '#18181b',
    overrideZincTextMuted: '#71717a',
  },
  cyber_purple: {
    id: 'cyber_purple',
    name: 'Retro Synthwave',
    description: 'Fuchsia neon glow on deep spatial zinc background',
    price: 250,
    bg: 'bg-zinc-950',
    cardBg: 'bg-zinc-900',
    border: 'border-zinc-800/80',
    text: 'text-zinc-100',
    textMuted: 'text-zinc-400',
    primaryBg: 'bg-fuchsia-600',
    primaryHoverBg: 'hover:bg-fuchsia-500',
    primaryText: 'text-white',
    accentText: 'text-fuchsia-400',
    accentBg: 'bg-fuchsia-500/10',
    accentBorder: 'border-fuchsia-500/30',
    accentRing: 'focus:ring-fuchsia-500',
    gradientFrom: 'from-fuchsia-500',
    gradientTo: 'to-purple-500',
    isLight: false,
    overrideCyan300: '#f472b6',
    overrideCyan400: '#e879f9',
    overrideCyan500: '#d946ef',
    overrideCyan600: '#c084fc',
    overrideCyanRgb: '217, 70, 239',
  },
  crimson_lava: {
    id: 'crimson_lava',
    name: 'Crimson Lava',
    description: 'A fierce dark volcanic theme with glowing lava-red details',
    price: 300,
    bg: 'bg-zinc-950',
    cardBg: 'bg-zinc-900',
    border: 'border-zinc-800',
    text: 'text-zinc-100',
    textMuted: 'text-zinc-400',
    primaryBg: 'bg-rose-600',
    primaryHoverBg: 'hover:bg-rose-500',
    primaryText: 'text-white',
    accentText: 'text-rose-400',
    accentBg: 'bg-rose-500/10',
    accentBorder: 'border-rose-500/30',
    accentRing: 'focus:ring-rose-500',
    gradientFrom: 'from-rose-500',
    gradientTo: 'to-orange-500',
    isLight: false,
    overrideCyan300: '#fda4af',
    overrideCyan400: '#fb7185',
    overrideCyan500: '#f43f5e',
    overrideCyan600: '#e11d48',
    overrideCyanRgb: '244, 63, 94',
  },
  electric_blue: {
    id: 'electric_blue',
    name: 'Electric Cyberpunk',
    description: 'Deep high-energy neon electric blue highlights',
    price: 220,
    bg: 'bg-zinc-950',
    cardBg: 'bg-zinc-900',
    border: 'border-zinc-800',
    text: 'text-zinc-100',
    textMuted: 'text-zinc-400',
    primaryBg: 'bg-blue-600',
    primaryHoverBg: 'hover:bg-blue-500',
    primaryText: 'text-white',
    accentText: 'text-cyan-400',
    accentBg: 'bg-cyan-500/10',
    accentBorder: 'border-cyan-500/30',
    accentRing: 'focus:ring-blue-500',
    gradientFrom: 'from-blue-600',
    gradientTo: 'to-cyan-400',
    isLight: false,
    overrideCyan300: '#93c5fd',
    overrideCyan400: '#60a5fa',
    overrideCyan500: '#3b82f6',
    overrideCyan600: '#1d4ed8',
    overrideCyanRgb: '59, 130, 246',
  },
  sunset_gold: {
    id: 'sunset_gold',
    name: 'Golden Hour',
    description: 'Warm gold and amber accents resembling a late summer sunset',
    price: 180,
    bg: 'bg-zinc-950',
    cardBg: 'bg-zinc-900',
    border: 'border-zinc-800',
    text: 'text-zinc-100',
    textMuted: 'text-zinc-400',
    primaryBg: 'bg-amber-500',
    primaryHoverBg: 'hover:bg-amber-400',
    primaryText: 'text-zinc-950',
    accentText: 'text-amber-400',
    accentBg: 'bg-amber-500/10',
    accentBorder: 'border-amber-500/30',
    accentRing: 'focus:ring-amber-500',
    gradientFrom: 'from-amber-500',
    gradientTo: 'to-yellow-300',
    isLight: false,
    overrideCyan300: '#fde047',
    overrideCyan400: '#fbbf24',
    overrideCyan500: '#f59e0b',
    overrideCyan600: '#d97706',
    overrideCyanRgb: '245, 158, 11',
  },
  toxic_slime: {
    id: 'toxic_slime',
    name: 'Acid Neon Green',
    description: 'High-intensity radioactive green neon highlights',
    price: 240,
    bg: 'bg-zinc-950',
    cardBg: 'bg-zinc-900',
    border: 'border-zinc-850',
    text: 'text-zinc-100',
    textMuted: 'text-zinc-400',
    primaryBg: 'bg-lime-500',
    primaryHoverBg: 'hover:bg-lime-450',
    primaryText: 'text-zinc-950',
    accentText: 'text-lime-400',
    accentBg: 'bg-lime-500/10',
    accentBorder: 'border-lime-500/30',
    accentRing: 'focus:ring-lime-500',
    gradientFrom: 'from-lime-500',
    gradientTo: 'to-emerald-400',
    isLight: false,
    overrideCyan300: '#bef264',
    overrideCyan400: '#a3e635',
    overrideCyan500: '#84cc16',
    overrideCyan600: '#65a30d',
    overrideCyanRgb: '132, 204, 22',
  },
  glacier_ice: {
    id: 'glacier_ice',
    name: 'Glacier Frost',
    description: 'Crisp cold winter styling with deep frozen ice gradients',
    price: 200,
    bg: 'bg-zinc-950',
    cardBg: 'bg-zinc-900',
    border: 'border-zinc-800',
    text: 'text-zinc-100',
    textMuted: 'text-zinc-400',
    primaryBg: 'bg-sky-500',
    primaryHoverBg: 'hover:bg-sky-400',
    primaryText: 'text-zinc-950',
    accentText: 'text-sky-400',
    accentBg: 'bg-sky-500/10',
    accentBorder: 'border-sky-500/30',
    accentRing: 'focus:ring-sky-500',
    gradientFrom: 'from-sky-500',
    gradientTo: 'to-cyan-300',
    isLight: false,
    overrideCyan300: '#bae6fd',
    overrideCyan400: '#38bdf8',
    overrideCyan500: '#0ea5e9',
    overrideCyan600: '#0284c7',
    overrideCyanRgb: '14, 165, 233',
  },
  royal_purple: {
    id: 'royal_purple',
    name: 'Imperial Violet',
    description: 'Regal deep violet base highlighted by luxurious royal accents',
    price: 280,
    bg: 'bg-zinc-950',
    cardBg: 'bg-zinc-900',
    border: 'border-zinc-800',
    text: 'text-zinc-100',
    textMuted: 'text-zinc-400',
    primaryBg: 'bg-violet-600',
    primaryHoverBg: 'hover:bg-violet-500',
    primaryText: 'text-white',
    accentText: 'text-violet-400',
    accentBg: 'bg-violet-500/10',
    accentBorder: 'border-violet-500/30',
    accentRing: 'focus:ring-violet-500',
    gradientFrom: 'from-violet-600',
    gradientTo: 'to-purple-400',
    isLight: false,
    overrideCyan300: '#c084fc',
    overrideCyan400: '#a855f7',
    overrideCyan500: '#9333ea',
    overrideCyan600: '#7e22ce',
    overrideCyanRgb: '147, 51, 234',
  },
  ocean_breeze: {
    id: 'ocean_breeze',
    name: 'Coral Navy',
    description: 'Subtle nautical navy background with rich coral pink accents',
    price: 260,
    bg: 'bg-zinc-950',
    cardBg: 'bg-zinc-900',
    border: 'border-zinc-800',
    text: 'text-zinc-100',
    textMuted: 'text-zinc-400',
    primaryBg: 'bg-rose-500',
    primaryHoverBg: 'hover:bg-rose-450',
    primaryText: 'text-white',
    accentText: 'text-rose-400',
    accentBg: 'bg-rose-500/10',
    accentBorder: 'border-rose-500/30',
    accentRing: 'focus:ring-rose-500',
    gradientFrom: 'from-rose-500',
    gradientTo: 'to-orange-400',
    isLight: false,
    overrideCyan300: '#fecdd3',
    overrideCyan400: '#fda4af',
    overrideCyan500: '#fb7185',
    overrideCyan600: '#f43f5e',
    overrideCyanRgb: '251, 113, 133',
  },
  retro_vintage: {
    id: 'retro_vintage',
    name: 'Sepia Vintage (Light)',
    description: 'An elegant retro light theme reminiscent of historic parchment',
    price: 320,
    bg: 'bg-amber-50/40',
    cardBg: 'bg-stone-100',
    border: 'border-stone-200',
    text: 'text-stone-900',
    textMuted: 'text-stone-500',
    primaryBg: 'bg-amber-700',
    primaryHoverBg: 'hover:bg-amber-600',
    primaryText: 'text-white',
    accentText: 'text-amber-800',
    accentBg: 'bg-amber-100/50',
    accentBorder: 'border-amber-300/40',
    accentRing: 'focus:ring-amber-600',
    gradientFrom: 'from-amber-600',
    gradientTo: 'to-stone-500',
    isLight: true,
    overrideCyan300: '#b45309',
    overrideCyan400: '#d97706',
    overrideCyan500: '#b45309',
    overrideCyan600: '#78350f',
    overrideCyanRgb: '180, 83, 9',
    overrideZincBackground: '#f5f5f4',
    overrideZincCardBg: '#fafaf9',
    overrideZincBorder: '#e7e5e4',
    overrideZincText: '#292524',
    overrideZincTextMuted: '#57534e',
  }
};
